name: Build containers and push to Docker Hub
on: 
  push:
    branches:
      - main
  schedule:
    - cron: 0 6 * * 6
      
jobs:
  build-containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version:
          - "22.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check if latest version
        id: latest
        run: |
          if [ $(cat latest.txt) = "${{ matrix.ubuntu_version }}" ] 
          then 
            echo "is=true" >> $GITHUB_OUTPUT
          else
            echo "is=false" >> $GITHUB_OUTPUT
          fi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Construct Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/builder
          tags: |
            type=raw,value=latest,enable=${{ steps.latest.outputs.is }}
            type=raw,value=${{ matrix.ubuntu_version }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BASEVERSION=${{ matrix.ubuntu_version }}
